# Generated by Django 5.2.1 on 2025-05-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='capital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='city_pictures/'),
        ),
    ]
