# Generated by Django 5.2.1 on 2025-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0002_city_capital_city_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
