# Generated by Django 5.2.1 on 2025-05-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakila', '0003_alter_city_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='city_pictures/'),
        ),
    ]
